import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("Starting database seed...");

  await prisma.orderStatusHistory.deleteMany();
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.topping.deleteMany();
  await prisma.menuItem.deleteMany();
  await prisma.promoCode.deleteMany();
  await prisma.deliveryZone.deleteMany();
  await prisma.adminUser.deleteMany();

  console.log("Cleared existing data");

  const toppings = [
    { toppingId: "chashu", name: "Extra Chashu", japanese: "チャーシュー", price: 3.0 },
    { toppingId: "egg", name: "Soft-Boiled Egg", japanese: "味玉", price: 1.5 },
    { toppingId: "noodles", name: "Extra Noodles", japanese: "替え玉", price: 2.0 },
    { toppingId: "nori", name: "Nori Sheets", japanese: "海苔", price: 1.0 },
    { toppingId: "corn", name: "Sweet Corn", japanese: "コーン", price: 1.0 },
    { toppingId: "bamboo", name: "Bamboo Shoots", japanese: "メンマ", price: 1.5 },
    { toppingId: "greenOnion", name: "Green Onions", japanese: "ネギ", price: 0 },
    { toppingId: "mushrooms", name: "Shiitake Mushrooms", japanese: "椎茸", price: 2.0 },
    { toppingId: "butter", name: "Butter", japanese: "バター", price: 0.5 },
    { toppingId: "garlic", name: "Roasted Garlic", japanese: "にんにく", price: 1.0 },
  ];

  for (const topping of toppings) {
    await prisma.topping.create({ data: topping });
  }
  console.log("Seeded toppings");

  const menuItems = [
    {
      slug: "tonkotsu-ramen",
      name: "Tonkotsu Ramen",
      japanese: "豚骨ラーメン",
      description: "Rich pork bone broth simmered for 18 hours with chashu, soft-boiled egg, green onions, and nori.",
      longDescription: "The art of Tonkotsu begins before dawn.",
      price: 14.99,
      rating: 4.9,
      reviewCount: 328,
      image: "/items/Tonkotsu.jpg",
      images: ["/items/Tonkotsu.jpg"],
      category: "ramen",
      bestseller: true,
      isNew: false,
      spicy: 0,
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      prepTime: 10,
      calories: 680,
      customizable: true,
      serves: 1,
      ingredients: ["Pork bone broth", "Chashu pork belly", "Ramen noodles"],
      allergens: ["Gluten", "Egg", "Soy", "Sesame"],
      nutrition: { calories: 680, protein: 32, carbs: 58, fat: 34, sodium: 1850 },
      pairings: [7, 10, 13],
      reviews: { rating: 4.9, count: 328, breakdown: { "5": 280, "4": 35, "3": 10, "2": 2, "1": 1 }, featured: [] }
    },
    {
      slug: "spicy-miso-ramen",
      name: "Spicy Miso Ramen",
      japanese: "辛味噌ラーメン",
      description: "Fermented soybean paste broth with ground pork, corn, butter, and spicy chili oil.",
      longDescription: "Our Spicy Miso Ramen is a celebration of Hokkaido.",
      price: 15.99,
      rating: 4.8,
      reviewCount: 256,
      image: "/items/spicyMiso.jpg",
      images: ["/items/spicyMiso.jpg"],
      category: "ramen",
      bestseller: false,
      isNew: false,
      spicy: 2,
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      prepTime: 12,
      calories: 720,
      customizable: true,
      serves: 1,
      ingredients: ["Miso paste", "Pork broth", "Ground pork"],
      allergens: ["Gluten", "Soy", "Dairy", "Sesame"],
      nutrition: { calories: 720, protein: 28, carbs: 62, fat: 38, sodium: 2100 },
      pairings: [8, 12, 7],
      reviews: { rating: 4.8, count: 256, breakdown: { "5": 200, "4": 40, "3": 12, "2": 3, "1": 1 }, featured: [] }
    },
    {
      slug: "shoyu-ramen",
      name: "Shoyu Ramen",
      japanese: "醤油ラーメン",
      description: "Classic soy sauce based broth with bamboo shoots, nori, and perfectly cooked noodles.",
      longDescription: "Shoyu Ramen represents the original Tokyo-style ramen.",
      price: 13.99,
      rating: 4.7,
      reviewCount: 189,
      image: "/items/shoyu.jpg",
      images: ["/items/shoyu.jpg"],
      category: "ramen",
      bestseller: false,
      isNew: false,
      spicy: 0,
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      prepTime: 10,
      calories: 580,
      customizable: true,
      serves: 1,
      ingredients: ["Chicken broth", "Dashi", "Soy sauce"],
      allergens: ["Gluten", "Egg", "Soy", "Fish"],
      nutrition: { calories: 580, protein: 26, carbs: 52, fat: 28, sodium: 1650 },
      pairings: [7, 8, 12],
      reviews: { rating: 4.7, count: 189, breakdown: { "5": 140, "4": 35, "3": 10, "2": 3, "1": 1 }, featured: [] }
    },
    {
      slug: "tantanmen",
      name: "Tantanmen",
      japanese: "担々麺",
      description: "Creamy sesame broth with spicy minced pork, bok choy, and aromatic chili crisp.",
      longDescription: "Tantanmen is our tribute to the Sichuan dan dan noodles.",
      price: 16.99,
      rating: 4.9,
      reviewCount: 412,
      image: "/items/tantanmen.jpg",
      images: ["/items/tantanmen.jpg"],
      category: "ramen",
      bestseller: true,
      isNew: false,
      spicy: 2,
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      prepTime: 12,
      calories: 750,
      customizable: true,
      serves: 1,
      ingredients: ["Sesame paste", "Chicken broth", "Chili oil"],
      allergens: ["Gluten", "Soy", "Sesame", "Peanuts"],
      nutrition: { calories: 750, protein: 30, carbs: 55, fat: 42, sodium: 1980 },
      pairings: [8, 11, 10],
      reviews: { rating: 4.9, count: 412, breakdown: { "5": 365, "4": 35, "3": 8, "2": 3, "1": 1 }, featured: [] }
    },
    {
      slug: "vegetable-miso-ramen",
      name: "Vegetable Miso Ramen",
      japanese: "野菜味噌ラーメン",
      description: "Hearty vegetable broth with tofu, seasonal vegetables, corn, and mushrooms.",
      longDescription: "Our Vegetable Miso Ramen proves plant-based can be satisfying.",
      price: 13.99,
      rating: 4.6,
      reviewCount: 124,
      image: "/items/vegetableMisoRamen.jpg",
      images: ["/items/vegetableMisoRamen.jpg"],
      category: "ramen",
      bestseller: false,
      isNew: true,
      spicy: 0,
      vegetarian: true,
      vegan: true,
      glutenFree: false,
      prepTime: 10,
      calories: 420,
      customizable: true,
      serves: 1,
      ingredients: ["Vegetable broth", "White miso", "Red miso"],
      allergens: ["Gluten", "Soy"],
      nutrition: { calories: 420, protein: 18, carbs: 52, fat: 16, sodium: 1450 },
      pairings: [8, 12, 16],
      reviews: { rating: 4.6, count: 124, breakdown: { "5": 85, "4": 28, "3": 8, "2": 2, "1": 1 }, featured: [] }
    },
    {
      slug: "black-garlic-ramen",
      name: "Black Garlic Ramen",
      japanese: "黒にんにくラーメン",
      description: "Bold tonkotsu base with black garlic oil, chashu, and caramelized onions.",
      longDescription: "Our Black Garlic Ramen is an indulgent masterpiece.",
      price: 17.99,
      rating: 4.8,
      reviewCount: 98,
      image: "/items/blackGarlicRamen.jpg",
      images: ["/items/blackGarlicRamen.jpg"],
      category: "ramen",
      bestseller: false,
      isNew: true,
      spicy: 1,
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      prepTime: 15,
      calories: 780,
      customizable: true,
      serves: 1,
      ingredients: ["Pork bone broth", "Black garlic oil"],
      allergens: ["Gluten", "Egg", "Soy", "Sesame"],
      nutrition: { calories: 780, protein: 34, carbs: 60, fat: 42, sodium: 1920 },
      pairings: [10, 13, 7],
      reviews: { rating: 4.8, count: 98, breakdown: { "5": 78, "4": 15, "3": 4, "2": 1, "1": 0 }, featured: [] }
    },
    {
      slug: "gyoza",
      name: "Gyoza (6 pcs)",
      japanese: "餃子",
      description: "Pan-fried pork and vegetable dumplings served with ponzu dipping sauce.",
      longDescription: "Our gyoza are a testament to the art of dumpling making.",
      price: 7.99,
      rating: 4.8,
      reviewCount: 567,
      image: "/items/gyoza.jpg",
      images: ["/items/gyoza.jpg"],
      category: "appetizers",
      bestseller: true,
      isNew: false,
      spicy: 0,
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      prepTime: 8,
      calories: 320,
      customizable: false,
      serves: 2,
      ingredients: ["Gyoza wrappers", "Ground pork"],
      allergens: ["Gluten", "Soy", "Sesame"],
      nutrition: { calories: 320, protein: 14, carbs: 28, fat: 18, sodium: 680 },
      pairings: [1, 3, 13],
      reviews: { rating: 4.8, count: 567, breakdown: { "5": 450, "4": 90, "3": 20, "2": 5, "1": 2 }, featured: [] }
    },
    {
      slug: "edamame",
      name: "Edamame",
      japanese: "枝豆",
      description: "Steamed young soybeans sprinkled with sea salt.",
      longDescription: "Simple, satisfying, and impossibly addictive.",
      price: 4.99,
      rating: 4.5,
      reviewCount: 234,
      image: "/items/edamame.jpg",
      images: ["/items/edamame.jpg"],
      category: "appetizers",
      bestseller: false,
      isNew: false,
      spicy: 0,
      vegetarian: true,
      vegan: true,
      glutenFree: true,
      prepTime: 5,
      calories: 120,
      customizable: false,
      serves: 2,
      ingredients: ["Young soybeans", "Sea salt"],
      allergens: ["Soy"],
      nutrition: { calories: 120, protein: 11, carbs: 9, fat: 5, sodium: 280 },
      pairings: [2, 4, 11],
      reviews: { rating: 4.5, count: 234, breakdown: { "5": 150, "4": 60, "3": 18, "2": 4, "1": 2 }, featured: [] }
    },
    {
      slug: "takoyaki",
      name: "Takoyaki (6 pcs)",
      japanese: "たこ焼き",
      description: "Crispy octopus balls topped with takoyaki sauce, mayo, and bonito flakes.",
      longDescription: "Transport yourself to the bustling streets of Osaka.",
      price: 8.99,
      rating: 4.7,
      reviewCount: 189,
      image: "/items/takoyaki.jpg",
      images: ["/items/takoyaki.jpg"],
      category: "appetizers",
      bestseller: false,
      isNew: false,
      spicy: 0,
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      prepTime: 10,
      calories: 380,
      customizable: false,
      serves: 2,
      ingredients: ["Wheat flour batter", "Octopus"],
      allergens: ["Gluten", "Egg", "Fish", "Shellfish", "Soy"],
      nutrition: { calories: 380, protein: 16, carbs: 42, fat: 16, sodium: 720 },
      pairings: [3, 11, 13],
      reviews: { rating: 4.7, count: 189, breakdown: { "5": 135, "4": 40, "3": 10, "2": 3, "1": 1 }, featured: [] }
    },
    {
      slug: "karaage",
      name: "Karaage Chicken",
      japanese: "唐揚げ",
      description: "Japanese fried chicken pieces marinated in soy, ginger, and garlic.",
      longDescription: "Karaage is Japan's answer to fried chicken.",
      price: 9.99,
      rating: 4.9,
      reviewCount: 345,
      image: "/items/karaage.jpg",
      images: ["/items/karaage.jpg"],
      category: "appetizers",
      bestseller: true,
      isNew: false,
      spicy: 0,
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      prepTime: 12,
      calories: 450,
      customizable: false,
      serves: 2,
      ingredients: ["Chicken thigh", "Soy sauce"],
      allergens: ["Soy", "Egg"],
      nutrition: { calories: 450, protein: 28, carbs: 22, fat: 28, sodium: 820 },
      pairings: [1, 6, 13],
      reviews: { rating: 4.9, count: 345, breakdown: { "5": 305, "4": 30, "3": 8, "2": 1, "1": 1 }, featured: [] }
    },
    {
      slug: "ramune-soda",
      name: "Ramune Soda",
      japanese: "ラムネ",
      description: "Classic Japanese marble soda. Available in Original, Strawberry, and Melon.",
      longDescription: "Ramune is more than just a soda.",
      price: 3.99,
      rating: 4.4,
      reviewCount: 156,
      image: "/items/ramuneSoda.webp",
      images: ["/items/ramuneSoda.webp"],
      category: "drinks",
      bestseller: false,
      isNew: false,
      spicy: 0,
      vegetarian: true,
      vegan: true,
      glutenFree: true,
      prepTime: 1,
      calories: 80,
      customizable: false,
      serves: 1,
      ingredients: ["Carbonated water", "Sugar"],
      allergens: [],
      nutrition: { calories: 80, protein: 0, carbs: 20, fat: 0, sodium: 10 },
      pairings: [4, 9, 10],
      reviews: { rating: 4.4, count: 156, breakdown: { "5": 85, "4": 45, "3": 20, "2": 4, "1": 2 }, featured: [] }
    },
    {
      slug: "japanese-green-tea",
      name: "Japanese Green Tea",
      japanese: "緑茶",
      description: "Freshly brewed premium Japanese green tea, served hot or cold.",
      longDescription: "Our green tea is sourced from Uji, Kyoto.",
      price: 2.99,
      rating: 4.6,
      reviewCount: 201,
      image: "/items/GreenTea.jpg",
      images: ["/items/GreenTea.jpg"],
      category: "drinks",
      bestseller: false,
      isNew: false,
      spicy: 0,
      vegetarian: true,
      vegan: true,
      glutenFree: true,
      prepTime: 2,
      calories: 0,
      customizable: false,
      serves: 1,
      ingredients: ["Premium sencha green tea leaves"],
      allergens: [],
      nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0, sodium: 0 },
      pairings: [1, 3, 14],
      reviews: { rating: 4.6, count: 201, breakdown: { "5": 130, "4": 50, "3": 15, "2": 4, "1": 2 }, featured: [] }
    },
    {
      slug: "asahi-beer",
      name: "Asahi Beer",
      japanese: "アサヒビール",
      description: "Crisp and refreshing Japanese lager. 330ml bottle.",
      longDescription: "Asahi Super Dry revolutionized the beer world.",
      price: 4.99,
      rating: 4.5,
      reviewCount: 178,
      image: "/items/asahiBeer.jpg",
      images: ["/items/asahiBeer.jpg"],
      category: "drinks",
      bestseller: false,
      isNew: false,
      spicy: 0,
      vegetarian: true,
      vegan: true,
      glutenFree: false,
      prepTime: 1,
      calories: 140,
      customizable: false,
      serves: 1,
      ingredients: ["Water", "Malted barley"],
      allergens: ["Gluten"],
      nutrition: { calories: 140, protein: 1, carbs: 10, fat: 0, sodium: 10 },
      pairings: [1, 6, 10],
      reviews: { rating: 4.5, count: 178, breakdown: { "5": 100, "4": 55, "3": 18, "2": 3, "1": 2 }, featured: [] }
    },
    {
      slug: "mochi-ice-cream",
      name: "Mochi Ice Cream (3 pcs)",
      japanese: "もちアイス",
      description: "Soft rice cake filled with ice cream. Matcha, vanilla, and strawberry.",
      longDescription: "Our mochi ice cream combines two beloved desserts.",
      price: 6.99,
      rating: 4.8,
      reviewCount: 289,
      image: "/items/mochiIceCream.jpg",
      images: ["/items/mochiIceCream.jpg"],
      category: "desserts",
      bestseller: true,
      isNew: false,
      spicy: 0,
      vegetarian: true,
      vegan: false,
      glutenFree: true,
      prepTime: 2,
      calories: 240,
      customizable: false,
      serves: 1,
      ingredients: ["Sweet rice flour", "Cream", "Milk"],
      allergens: ["Dairy"],
      nutrition: { calories: 240, protein: 4, carbs: 36, fat: 9, sodium: 45 },
      pairings: [12, 1, 4],
      reviews: { rating: 4.8, count: 289, breakdown: { "5": 230, "4": 45, "3": 10, "2": 3, "1": 1 }, featured: [] }
    },
    {
      slug: "matcha-cheesecake",
      name: "Matcha Cheesecake",
      japanese: "抹茶チーズケーキ",
      description: "Creamy Japanese-style cheesecake with premium matcha green tea.",
      longDescription: "Our Matcha Cheesecake is a fusion of traditions.",
      price: 7.99,
      rating: 4.7,
      reviewCount: 167,
      image: "/items/matchaCheescake.jpg",
      images: ["/items/matchaCheescake.jpg"],
      category: "desserts",
      bestseller: false,
      isNew: true,
      spicy: 0,
      vegetarian: true,
      vegan: false,
      glutenFree: false,
      prepTime: 3,
      calories: 320,
      customizable: false,
      serves: 1,
      ingredients: ["Cream cheese", "Eggs", "Matcha powder"],
      allergens: ["Dairy", "Egg", "Gluten"],
      nutrition: { calories: 320, protein: 6, carbs: 28, fat: 21, sodium: 220 },
      pairings: [12, 5, 3],
      reviews: { rating: 4.7, count: 167, breakdown: { "5": 120, "4": 35, "3": 9, "2": 2, "1": 1 }, featured: [] }
    },
    {
      slug: "dorayaki",
      name: "Dorayaki",
      japanese: "どら焼き",
      description: "Traditional Japanese pancake sandwich filled with sweet red bean paste.",
      longDescription: "Dorayaki holds a special place in Japanese culture.",
      price: 4.99,
      rating: 4.6,
      reviewCount: 134,
      image: "/items/daroyaki.jpg",
      images: ["/items/daroyaki.jpg"],
      category: "desserts",
      bestseller: false,
      isNew: false,
      spicy: 0,
      vegetarian: true,
      vegan: false,
      glutenFree: false,
      prepTime: 2,
      calories: 280,
      customizable: false,
      serves: 1,
      ingredients: ["Flour", "Eggs", "Azuki red beans"],
      allergens: ["Gluten", "Egg"],
      nutrition: { calories: 280, protein: 7, carbs: 52, fat: 4, sodium: 180 },
      pairings: [12, 1, 5],
      reviews: { rating: 4.6, count: 134, breakdown: { "5": 90, "4": 32, "3": 9, "2": 2, "1": 1 }, featured: [] }
    },
  ];

  for (const item of menuItems) {
    await prisma.menuItem.create({ data: item });
  }
  console.log("Seeded menu items");

  const promoCodes = [
    {
      code: "WELCOME10",
      discountType: "PERCENT" as const,
      discountValue: 10,
      description: "10% off your first order!",
      minOrder: 15,
      maxDiscount: 20,
      usageLimit: 1000,
      validUntil: new Date("2026-12-31"),
    },
    {
      code: "YUME5",
      discountType: "FIXED" as const,
      discountValue: 5,
      description: "EUR 5.00 off your order!",
      minOrder: 25,
      usageLimit: 500,
      validUntil: new Date("2026-06-30"),
    },
    {
      code: "FREESHIP",
      discountType: "FREE_DELIVERY" as const,
      discountValue: 0,
      description: "Free delivery on this order!",
      minOrder: 30,
      usageLimit: 200,
      validUntil: new Date("2026-03-31"),
    },
  ];

  for (const promo of promoCodes) {
    await prisma.promoCode.create({ data: promo });
  }
  console.log("Seeded promo codes");

  const deliveryZones = [
    { postalCode: "1011", fee: 0, estimatedTime: 25, minOrder: 15 },
    { postalCode: "1012", fee: 0, estimatedTime: 25, minOrder: 15 },
    { postalCode: "1013", fee: 0, estimatedTime: 25, minOrder: 15 },
    { postalCode: "1014", fee: 1.5, estimatedTime: 30, minOrder: 15 },
    { postalCode: "1015", fee: 1.5, estimatedTime: 30, minOrder: 15 },
    { postalCode: "1016", fee: 1.5, estimatedTime: 30, minOrder: 15 },
    { postalCode: "1017", fee: 2.5, estimatedTime: 35, minOrder: 20 },
    { postalCode: "1018", fee: 2.5, estimatedTime: 35, minOrder: 20 },
    { postalCode: "1019", fee: 2.5, estimatedTime: 35, minOrder: 20 },
    { postalCode: "1051", fee: 3.5, estimatedTime: 40, minOrder: 25 },
    { postalCode: "1052", fee: 3.5, estimatedTime: 40, minOrder: 25 },
    { postalCode: "1053", fee: 3.5, estimatedTime: 40, minOrder: 25 },
    { postalCode: "1054", fee: 4.5, estimatedTime: 45, minOrder: 25 },
    { postalCode: "1055", fee: 4.5, estimatedTime: 45, minOrder: 25 },
    { postalCode: "1056", fee: 5.5, estimatedTime: 50, minOrder: 30 },
    { postalCode: "1057", fee: 5.5, estimatedTime: 50, minOrder: 30 },
    { postalCode: "1058", fee: 5.5, estimatedTime: 50, minOrder: 30 },
  ];

  for (const zone of deliveryZones) {
    await prisma.deliveryZone.create({ data: zone });
  }
  console.log("Seeded delivery zones");

  const adminPassword = await bcrypt.hash(process.env.ADMIN_PASSWORD || "bingbong13", 12);
  await prisma.adminUser.create({
    data: {
      email: process.env.ADMIN_EMAIL || "123@gmail.com",
      password: adminPassword,
      name: "Yume Admin",
      role: "ADMIN",
    },
  });
  console.log("Seeded admin user");

  console.log("Database seeding completed!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
